# Declare characters used by this game.
define aliya = Character("Aliya", color = "#ff5e27", who_bold=True)
define nat = Character("Nat", color = "#ff5e27", who_bold=True)
define riverman = Character('Riverman', color="#ff5e27", who_bold=True)
define unknown = Character("???", color = "#ff5e27", who_bold=True)
define man = Character("Man", color = "#ff5e27", image="bubble", kind=bubble)
define woman = Character("Woman", color = "#ff5e27", image="bubble", kind=bubble)
define owner = Character("Owner", color = "#ff5e27", who_bold=True)
define monkey = Character("Monkey", color = "#ff5e27", who_bold=True)
define ted = Character("Smol Ted", color = "#ff5e27", who_bold=True)
define vendor = Character("Vendor", color = "#ff5e27", who_bold=True)
define toad = Character("Toad", color = "#ff5e27", who_bold=True)
define guard = Character("Guard Captain", color = "#ff5e27", who_bold=True)
define storyteller = Character("Narrator", color = "#d79b3b", who_bold=True)
define congrats = Character("Congratulations!", color = "#43211b", who_bold=True)
